### ISSUE TITLE
no need for ssl in mInputSocket

### ISSUE THREAD

**Issue by ghost** [GreenSnakeLinux/LG_WebOS_Remote#2]
Hello
Why are u using ssl socket factory in mInputSocket in the connect pointer method?
it is also working without the SSL.
(actually the ssl isn't connecting for me)

**Comment by GreenSnakeLinux** [comment]
Hello,
This code comes from LG SDK, this part with SSL is not working currently. So did you manage to make it work in removing the ssl part ??
I don't own a LG tv myself, i made this project for person that can help me to debug.

**Comment by GreenSnakeLinux** [comment]
Hello,
I have updated the code to remove the SSL part, can you test it ?
thanks

**Comment by ghost** [comment]
Sorry but I don't have this television. I had it on my parents house and tried to make this repo work for them.
